{% set name = "cunumeric" %}
{% if gpu_enabled == "true" %}
  {% set gpu_enabled_bool = true %}
{% elif gpu_enabled == "false" %}
  {% set gpu_enabled_bool = false %}
{% else %}
  {# We need to have a default value for the initial pass over the recipe #}
  {% set gpu_enabled_bool = false %}
{% endif %}
## The placeholder version is strictly for making two-pass conda build process.
## It should not be used for any other purpose, and this is not a default version.
{% set placeholder_version = '0.0.0.dev' %}
{% set default_cuda_version = '11.5' %}
{% set cuda_version='.'.join(environ.get('CUDA', default_cuda_version).split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set py_version=environ.get('CONDA_PY', '') %}
{% if build_number is defined %}
    {# do nothing if defined #}
{% else %}
    {% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% endif %}
{% if package_version is defined %}
    {% set version = package_version %}
    {% set core_version = version %}
## The tag must be in one of the two formats (where N is a digit):
## vNN.NN.NN
## vNN.NN.NN.dev

## Note: default values are only given to make conda build work. They should not be necessary in principle.
{% elif 'dev' in environ.get('GIT_DESCRIBE_TAG', placeholder_version) %}
    {% set version = (environ.get('GIT_DESCRIBE_TAG', placeholder_version) ~ environ.get('GIT_DESCRIBE_NUMBER', '')).lstrip('v') %}
    {% set core_version = (version.rsplit('.',1)[0] ~ ".dev" ~ "|>=" ~ version.rsplit('.',1)[0]) %}
{% else %}
    {% set version = environ.get('GIT_DESCRIBE_TAG', placeholder_version).lstrip('v') %}
    {% set core_version = version %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
{% if package_tar is defined %}
  url: {{ package_tar }}
{% else %}
  git_url: ../../
{% endif %}

build:
  skip: true # [not linux]
  number: {{ build_number }}
  missing_dso_whitelist:
    -  '*libcuda.so*'
{% if not gpu_enabled_bool %}
  string: "cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ PKG_BUILDNUM }}_cpu"
{% else %}
  string: "cuda{{ cuda_major }}_py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ PKG_BUILDNUM }}"
{% endif %}
{% if not gpu_enabled_bool %}
  track_features:
    - cpu_only
  script_env:
    - CPU_ONLY=1
{% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
{% if gpu_enabled_bool %}
    - cuda-nvcc ={{ cuda_version }}
{% endif %}
  host:
    - python
    - openblas =* =*openmp*
{% if not gpu_enabled_bool %}
    - legate-core >={{ core_version }} =*_cpu
{% else %}
    - legate-core >={{ core_version }}
    - cuda-driver-dev ={{ cuda_version }}
    - cuda-cudart-dev ={{ cuda_version }}
    # - libcutensor-dev >=1.3
    - cutensor >=1.3
    - cuda-nvtx
    - libcublas-dev
    - libcusolver-dev
    - libcufft-dev
    - nccl
{% endif %}

  run:
    - numpy >=1.22
    - libopenblas =* =*openmp*
{% if gpu_enabled_bool %}
    - cuda-cudart >={{ cuda_version }}
    # - libcutensor >=1.3
    - cutensor >=1.3
    - libcublas
    - libcusolver
    - libcufft
{% endif %}
    - opt_einsum >=3.3
    - scipy
    - typing_extensions

  run_constrained:
{% if gpu_enabled_bool %}
    - __cuda >=11.4
{% endif %}
    - __glibc >=2.17  # [linux]

about:
  home: https://github.com/nv-legate/cunumeric
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Drop-in Replacment for NumPy'
  description: |
    cuNumeric is a Legate library that aims to provide
    a distributed and accelerated drop-in replacement
    for the NumPy API on top of the Legion runtime.
  doc_url: https://github.com/nv-legate/cunumeric
  dev_url: https://github.com/nv-legate/cunumeric

extra:
  recipe-maintainers:
    - m3vaz
