name: Bug report
description: Submit a bug report
title: "[BUG] "
labels: TRIAGE
body:
  - type: markdown
    attributes:
      value: "# Bug report"
  - type: markdown
    attributes:
      value: Thank you for reporting a bug and helping us improve Cunumeric!
  - type: markdown
    attributes:
      value: >
        Please fill out all of the required information.
  - type: markdown
    attributes:
      value: |
        ---
        ## Environment information
  - type: textarea
    id: legate_issue
    attributes:
      label: Software versions
      description: >-
        Run `legate-issue` and paste the output here.
      placeholder: |
        Python      :  3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
        Platform    :  Linux-5.14.0-1042-oem-x86_64-with-glibc2.31
        Legion      :  v23.11.00.dev-16-g2499f878
        Legate      :  23.11.00.dev+17.gb7b50313
        Cunumeric   :  (ImportError: cannot import name 'LogicalArray' from 'legate.core')
        Numpy       :  1.24.4
        Scipy       :  1.10.1
        Numba       :  (not installed)
        CTK package : cuda-version-11.8-h70ddcb2_2 (conda-forge)
        GPU Driver  : 515.65.01
        GPU Devices :
          GPU 0: Quadro RTX 8000
          GPU 1: Quadro RTX 8000
    validations:
      required: true
  - type: input
    id: jupyter
    attributes:
      label: Jupyter notebook / Jupyter Lab version
      description: >-
        Please supply if the issue you are reporting is related to Jupyter
        notebook or Jupyter Lab.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Issue details
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: observed-behavior
    attributes:
      label: Observed behavior
      description: What did actually happen?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Directions to reproduce
  - type: textarea
    id: example
    attributes:
      label: Example code or instructions
      description: >
        Please provide detailed instructions to reproduce the issue. Ideally this includes a 
        [Complete, minimal, self-contained example code](https://stackoverflow.com/help/minimal-reproducible-example)
        given here or as a link to code in another repository. 
      render: Python
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Additional information
  - type: textarea
    id: traceback-console
    attributes:
      label: Stack traceback or browser console output
      description: >
        Add any error messages or logs that might be helpful in reproducing and
        identifying the bug, for example a Python stack traceback.
    validations:
      required: false
