#!/bin/bash

set -xeo pipefail

export CUDA_VERSION="12.0"
export CUDA_VERSION_MAJOR="12"
export CUDA_VERSION_MINOR="0"
export SCCACHE_REGION="us-east-2"
export SCCACHE_BUCKET="rapids-sccache-devs"
export SCCACHE_S3_KEY_PREFIX="legate-cunumeric-dev"
export USE_CUDA="ON"
export VAULT_HOST="https://vault.ops.k8s.rapids.ai"


cd ~
sudo cp -r ~/.artifacts/cunumeric/ .
sudo chown coder:coder ~/.artifacts
sudo chown -R coder:coder cunumeric/
cd .artifacts
rm -rf legate_core *.zip out/
# download_artifact https://github.com/nv-legate/legate.core/suites/16118272502/artifacts/920217985
download_artifact https://github.com/nv-legate/cunumeric/suites/16453466414/artifacts/940278627
unzip *.zip
# mv conda-build/legate_core .
cd ..

# env

sudo chown -R coder:coder ~/.artifacts



# entrypoint build-cunumeric-all
