#!/usr/bin/env bash

setup_env() {
    yaml_file=$(find ~/.artifacts -name "environment*.yaml" | head -n 1)
    mamba env create -n legate -f "$yaml_file"
    mamba uninstall -yn legate numpy
    mamba install -yn legate -c ~/.artifacts/legate_core -c ~/.artifacts/cunumeric -c conda-forge -c nvidia legate-core cunumeric

    set +u
    mamba activate legate;
    conda info;
    set -u
}

test-cunumeric() {
    set -x

    setup_env;

    cd ~/cunumeric;

    set -xeuo pipefail

    case "$1" in
        "test")
            echo "Executing tests..."
            shift;
            ./test.py --verbose "$@"
            ;;
        "mypy")
            echo "Executing mypy..."
            shift;
            mypy cunumeric
            ;;
        "docs")
            echo "Building docs..."
            shift;
            update_conda_env_using_section docs
            cd docs/cunumeric
            make clean html
            ;;
        *)
            echo "Invalid command: $1"
            return 1
            ;;
    esac
}

(test-cunumeric "$@");