name: setup-legate-conda

description: Download dependencies (artifacts)

inputs:
  device: {type: string, required: true}
  git_sha: {type: string, required: true}

runs:
  using: composite
  steps:

    - id: cache
      name: Cache conda artifacts
      uses: actions/cache@v3
      with:
        key: "nv-legate/legate.core@${{ inputs.git_sha }}-${{ inputs.device }}"
        path: .artifacts

    - if: steps.cache.outputs.cache-hit != 'true'
      name: Download conda artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        path: .artifacts-dl
        repo: nv-legate/legate.core
        commit: ${{ inputs.git_sha }}
        workflow_conclusion: success
        workflow: "ci-gh.yml"
        name: "legate.core-${{ inputs.device }}-[0-9a-z]{40}"
        name_is_regexp: true

    - if: steps.cache.outputs.cache-hit != 'true'
      name: Move conda artifacts into cached dir
      shell: bash --noprofile --norc -xeo pipefail {0}
      run: |
        mkdir -p .artifacts;
        find .artifacts-dl/legate.core-${{ inputs.device }}-*/ \
          -maxdepth 2 -type d -name legate_core -exec mv {} .artifacts/ \;
        find .artifacts-dl/legate.core-${{ inputs.device }}-*/ \
          -maxdepth 2 -type f -name "environment*.yaml" -exec mv {} .artifacts/ \;

    - name: Copy and change cache dir ownership
      shell: bash --noprofile --norc -xeo pipefail {0}
      run: |
        # Copy and change directory ownership
        cp -ar .artifacts /home/coder/.artifacts;
        chown -R coder:coder /home/coder/.artifacts;
        ls -R /home/coder/.artifacts
