#!/usr/bin/env bash

setup_env() {
    yaml_file=$(find ~/.artifacts -name "environment*.yaml" | head -n 1)
    mamba env create -n legate -f "$yaml_file"
    mamba uninstall -yn legate numpy
    mamba install -yn legate -c ~/.artifacts/legate_core -c conda-forge -c nvidia legate-core

    set +u
    mamba activate legate
    set -u
}

build_cunumeric_all() {
    setup_env;
    cd ~/cunumeric;
    conda info;

    set -xeuo pipefail;
    printf "\n\n\n\n********* BUILDING CUNUMERIC CPP *********"
    build-cunumeric-cpp;
    printf "\n\n\n\n********* BUILDING CUNUMERIC WHEEL *********"
    build-cunumeric-wheel;
    printf "\n\n\n\n********* BUILDING CUNUMERIC CONDA *********"
    build-cunumeric-conda;
}

(build_cunumeric_all "$@");
