name: Build and test cunumeric (with GPU legate) on GH

concurrency:
  group: ci-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

jobs:
  build-gpu:
    uses:
      ./.github/workflows/gh-build.yml
    with:
      build-target: gpu
      # Ref: https://docs.rapids.ai/resources/github-actions/#cpu-labels for `linux-amd64-cpu4`
      runs-on: ${{ github.repository_owner == 'nv-legate' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
      sha: ${{ github.sha }}

  cleanup:
    needs:
      - build-gpu

    # This ensures the cleanup job runs even if previous jobs fail or the workflow is cancelled.
    if: always()
    uses:
      ./.github/workflows/gh-cleanup.yml
    with:
      build-target: gpu
      sha: ${{ github.sha }}
