name: Build and test GPU cunumeric on GH

concurrency:
  group: ci-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"

jobs:
  build-gpu:
    uses:
      ./.github/workflows/gh-build.yml
    with:
      build-target: gpu
      # Ref: https://docs.rapids.ai/resources/github-actions/#cpu-labels for `linux-amd64-cpu4`
      runs-on: ${{ github.repository_owner == 'nv-legate' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}

  test-gpu:
    needs:
      - build-gpu
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 1 CPU test, options: --cpus 1 --unit --debug}
          - {name: 2 CPUs test, options: --cpus 2 --debug}
          - {name: GPU test, options: --use cuda --gpus 1 --debug}
          - {name: 2 GPUs test, options: --use cuda --gpus 2 --debug}
          - {name: OpenMP test, options: --use openmp --omps 1 --ompthreads 2 --debug}
          - {name: 2 NUMA OpenMPs test, options: --use openmp --omps 2 --ompthreads 2 --numamem 2048 --debug}
          - {name: Eager execution test, options: --use eager --debug}
    uses:
      ./.github/workflows/gh-test.yml
    with:
      build-target: gpu
      runs-on: linux-amd64-gpu-v100-latest-1
      test-name: ${{matrix.name}}
      test-options: ${{matrix.options}}

