name: Clean up

on:
  workflow_call:
    inputs:
      build-target:
        required: true
        type: string
      sha:
        required: true
        type: string

env:
  IMAGE_NAME: cunumeric-${{ inputs.build-target }}

jobs:
  cleanup:
    permissions:
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Delete docker image
        run: |
          set -xeuo pipefail

          PACKAGE_NAME=${{ env.IMAGE_NAME }}
          PACKAGE_VERSION_ID=$(
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME/versions |
            jq '.[] | select(.metadata.container.tags[] == "${{ inputs.sha }}") | .id' -
          )

          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME/versions/$PACKAGE_VERSION_ID
