name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: "category:new-feature, category:improvement, category:bug-fix, category:task, category:documentation"
          