name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Delay checking labels if PR is just created
        if: ${{ github.event.action == 'opened' }}
        run: sleep 300s
        shell: bash
      - name: Check Labels
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "category:new-feature, category:improvement, category:bug-fix, category:task"